version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-note:latest
    container_name: nextjs-note
    ports:
      - '4001:4001'
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}

      # - DATABASE_URL=${DATABASE_URL}
      # DATABASE_URL="mysql://root:root@localhost:3306/notes"

      - DATABASE_URL=${DATABASE_URL}
      # - DATABASE_URL=mysql://root:root@已存在的MySQL容器名:3306/notes
      # - DATABASE_URL=mysql://notes:notes12300@mysql9:3306/notes
      # 可以在容器中，通过 ping mysql9[容器名] 测试网络是否连接成功

      - AUTH_URL=${AUTH_URL}
      - NODE_ENV=production
    # restart: unless-stopped
    networks:
      # - app-network
      - mysql9-network

# networks:
#   app-network:
#     driver: bridge

networks:
  mysql9-network: # 直接使用实际网络名
    external: true # 使用外部已存在的网络

