import type { Metadata } from 'next';
import { Inter, Fira_Code } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

/**
 * https://nextjs.org/docs/app/api-reference/components/font#font-function-arguments
 *
 * 可变字体可以自由调整字宽、字重、倾斜等，从而实现一款字体展示出多款字体的效果。Next.js 推荐使用可变字体。
 *
 * Inter 是 Google Fonts 提供的一款可变字体，支持 100-900 的字重，以及斜体。
 *
 * 可变字体：https://fonts.google.com/variablefonts
 */

const inter = Inter({
  /**
   * 用于指定要加载的字符串（字体的子集）
   *
   * 谷歌的字体是可以指定子集（subset）的，
   * 就比如 Roboto Mono 支持拉丁文、西里尔文和希腊文等，
   * 我们没有必要都用到，就可以使用 subsets 属性指定某个子集，还可以减少字体文件的大小并改善性能。
   *
   * 常见值: latin(英文)、latin-ext(扩展拉丁)、cyrillic(西里尔)、greek(希腊) 等
   * 建议只加载你网站需要的字符集
   */
  subsets: ['latin'],
  /**
   * 指定要加载的字重，可以是单个值或数组，常见值: 100(Thin) 到 900(Black)。
   * 每增加一个字重都会增加总体积,建议只加载需要的。
   * 默认情况下，如果不配置 weight 属性，Next.js 会加载所有字重。
   */
  weight: ['300', '400', '500', '600', '700'],

  /**
   * 控制字体样式。
   * 可选值: normal, italic
   */
  style: ['normal'],

  /**
   * 控制字体加载时的渲染行为
   *  - swap: 先用后备字体,加载完后替换(推荐)
   *  - block: 短暂空白后显示
   *  - fallback: 短暂显示后备字体
   *  - optional: 根据网络条件决定是否加载
   */
  display: 'swap',

  /**
   * 是否预加载字体文件
   * 默认为 true
   */
  preload: true,

  /**
   * 指定 CSS 变量名
   * 用于在 CSS 中引用字体
   * 格式必须是 --font-{name}
   */
  variable: '--font-inter',

  /**
   * 定义后备字体，字体加载失败时使用
   */
  fallback: ['sans-serif', 'arial'],

  /**
   * 是否自动调整后备字体大小以匹配 web 字体，默认 true
   */
  adjustFontFallback: true,
});

const firaCode = Fira_Code({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, firaCode.className, 'min-h-screen')}>{children}</body>
    </html>
  );
}
