import type { Metadata } from 'next';

import './globals.css';
import clsx from 'clsx';
import { fontFamilyClassName } from '@/app/styles/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(fontFamilyClassName, 'min-h-screen')}>{children}</body>
    </html>
  );
}
